### ISSUE TITLE
WebP in Mac OS and Windows

### ISSUE THREAD

**Issue by kix2902** [PintaProject/Pinta-Community-Addins#7]
Is there any plan to update WebP add-in to work in Mac OS and Windows? Or any advise to update the extension by myself in local to let it working?

**Comment by robpvn** [comment]
You'd want to look at the WebP add-in repository: https://github.com/PintaProject/WebPAddin/issues/3 . But in general I don't think there is much work going on, no. (The issue there does have a little hint, but I don't know anything more than that.)
