### ISSUE TITLE
Add-In manager button not showing in Pinta 2.0.2 (Flatpak)

### ISSUE THREAD

**Issue by LavaHoleD** [PintaProject/Pinta-Community-Addins#8]
Hello, I am new to Pinta. I used to work on Windows with paint.NET, but after performance issues and more I decided to switch to Linux, where paint.NET isn't compatible.
I found about this project and I immediately installed it, and I gotta say that you guys did a very good job!
I immediately noticed that there was a lack of effects and such, and I found about the existance of "add-ins".
However, unlike everyone else (at least as what it seems) and the documentation itself the add-in manager button does not show. I tried searching around but there does not to be such feature.
Was it removed or is there some sort of issue?

I use Pop!_OS as my distro.

**Comment by cameronwhite** [comment]
Yes, unfortunately it had to be disabled due to technical reasons in v2.0, but hopefully it can be restored sometime soon once the dependencies are updated to support more recent GTK and .NET versions (https://groups.google.com/g/pinta-project/c/cYBTK7VBqko/m/v0jEIlLnAAAJ)

**Comment by DraconicNEO** [comment]
> Yes, unfortunately it had to be disabled due to technical reasons in v2.0, but hopefully it can be restored sometime soon once the dependencies are updated to support more recent GTK and .NET versions (https://groups.google.com/g/pinta-project/c/cYBTK7VBqko/m/v0jEIlLnAAAJ)

Are there any updates on how that's going, I mean it's been almost a year and still nothing. Doesn't seem like it's coming back, hope I'm wrong though.

**Comment by cameronwhite** [comment]
The `Mono.Addins` library has since been updated to target `netstandard-2.0`, so that should be compatible with Pinta's usage of .NET 6/7 now (although testing would be needed of course). The UI for managing add-ins would still need to be ported to GTK3, though

**Comment by u5n** [comment]
@cameronwhite , I'm using ubuntu, and my snap installs pinta 2.1.1. I can't find the addin manager either.
Can you tell me how to install an addin manually?

**Comment by cameronwhite** [comment]
There is not any support for add-ins (including manual installation) in Pinta 2.1.
Support for add-ins has been restored in the upcoming Pinta 2.2 release
